# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            reesjones
tagline:       	  Mitch Rees-Jones, software & web developer at NC State
description:      "The temporary personal site of Mitch Rees-Jones"
url:              url
baseurl:          /

author:
  name:           'Mitch Rees-Jones'
  url:            https://reesjones.github.io

paginate:         4

# Custom vars
version:          1.0.0

github:           https://github.com/reesjones/
linkedin:		  https://www.linkedin.com/in/reesjones
