# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            reesjones
tagline:       	  Mitch Rees-Jones, software & web developer at NC State
description:      "Mitch Rees-Jones, software/web/mobile developer at NC State"
url:              url
baseurl:          /

author:
  name:           'Mitch Rees-Jones'
  url:            https://reesjones.github.io

paginate:         4

# Custom vars

github:           https://github.com/reesjones/
linkedin:		  https://www.linkedin.com/in/reesjones
